DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NOME VARCHAR(250) DEFAULT NULL,
  LOGIN VARCHAR(250) DEFAULT NULL,
  SENHA VARCHAR(250) DEFAULT NULL,
  DH_CRIACAO TIMESTAMP DEFAULT NULL,
  DH_ALTERACAO TIMESTAMP DEFAULT NULL
);

INSERT INTO USUARIO (NOME, LOGIN, SENHA) VALUES
  ('Alisom', 'teste', '12345'),
  ('Talis', 'hello', '12345'),
  ('Tigas', 'word', '12345');